### PR TITLE
feat(*): add diff output for "toHaveBeenCalledWith" matcher

### PR DESCRIPTION
**Pull request by darlanalves**
@jimf Thanks for this awesome module!

I took the time today to add a diff on `toHaveBeenCalledWith` method.
Checking for arguments is often worse than value comparisons due to multiple calls being checked.

### CODE REVIEW

**Comment by jimf** [comment]
Thanks! I'm out of town for the long weekend, but I'll try to take a look next week.

**Comment by jimf** [comment]
Looks like this project has bit-rotted a bit since I last looked at it, and tests are now failing on master. I'm going to see about tackling that first.

**Comment by darlanalves** [comment]
@jimf thanks!
I updated my PR with upstream and fixed the broken specs.
I need a bit of help in adding test coverage for it. I couldn't follow much on how comparisons work here.

**Comment by jimf** [comment]
Hey @darlanalves. Sorry, I've been slow to follow up on this. There are a number of considerations to make with this feature, and I don't want to rush it. Some things that come to mind:

1. Is the case handled where `actual` isn't a proper spy?
1. What happens/should happen in the negated case, i.e., `.not.toHaveBeenCalledWith(...)`?
1. What happens/should happen when multiple arguments are expected/passed?
1. Along with the previous bullet, what happens/should happen when some but not all args match?
1. What happens/should happen when fuzzy matching, e.g., `objectContaining`

Truthfully, I'm not even 100% sure the existing `toBe` and `toEqual` work 100% as desired with these cases, but I'd like to at least think about them. Likely I'll defer to what Jest does, as I've pretty much moved exclusively to that in new projects and think they handle diffing very nicely.

As an aside, I'd also prefer to keep the strategy of adding extra annotation to existing messages than build in additional matcher logic, in the aim of resiliency to upstream changes in Jasmine core. I threw a little bit together, but haven't run through all the cases:

```diff
diff --git i/index.js w/index.js
index 11b55ef..dfb9be1 100644
--- i/index.js
+++ w/index.js
@@ -430,8 +430,45 @@ module.exports = function jasmineDiffMatchers (j$, options) {
     }
   }

+  function createCallMatcher (origFn, desc) {
+    return function (util, customEqualityTesters) {
+      return {
+        compare: function () {
+          var args = Array.prototype.slice.call(arguments)
+          var actual = args[0]
+          var expected = args.slice(1)
+          var result = origFn(util, customEqualityTesters).compare.apply(null, args)
+
+          if (result.pass || !isDiffable(expected)) {
+            return result
+          }
+
+          var expectedStr = stringify(expected)
+          var origResultMessage = result.message
+
+          result.message = function () {
+            var message = origResultMessage()
+            actual.calls.allArgs().forEach(function (actualArgs) {
+              var argsDiff
+              if (isDiffable(actualArgs)) {
+                argsDiff = errorDiff(stringify(actualArgs), expectedStr, annotateAdd, annotateRemove)
+                if (argsDiff) {
+                  message += '\n\n' + argsDiff
+                }
+              }
+            })
+            return message
+          }
+
+          return result
+        }
+      }
+    }
+  }
+
   return {
     toBe: createMatcher(j$.matchers.toBe, 'to be'),
-    toEqual: createMatcher(j$.matchers.toEqual, 'to equal')
+    toEqual: createMatcher(j$.matchers.toEqual, 'to equal'),
+    toHaveBeenCalledWith: createCallMatcher(j$.matchers.toHaveBeenCalledWith, 'to have been called with')
   }
 }
```

Don't sweat the testing too much. I can always follow up on that. Something to note is that for the functional tests, the "fixtures" are much more akin to Jest snapshots, but without all the ergonomics that Jest provides. My workflow is basically to run `node test/functional/index.js` and eyeball the output to make sure it looks like I'd expect, and then run `npm run update-fixtures` to update. You may have figured this out. I just want to call it out since I don't have it documented, which I probably should do.

**Pull request closed without merging**
